module.exports = {
    JOB_STATUS: {
        SCHEDULED: "SCHEDULED",
        RUNNING: "RUNNING",
        CANCELLED: "CANCELLED",
        COMPLETED: "COMPLETED",
        ERROR: "ERROR",
        STARTED_POSTPROCESSING: "STARTED_POSTPROCESSING",
        COMPLETED_POSTPROCESSING: "COMPLETED_POSTPROCESSING"
    },
    JOB_TYPE: {
        MEDIA_TRANSCRIPTION: "MEDIA_TRANSCRIPTION",
        MANUAL_ARTICLE_CREATION: "MANUAL_ARTICLE_CREATION",
        AUTOMATIC_ARTICLE_CREATION: "AUTOMATIC_ARTICLE_CREATION",
        STREAM_ARTICLE_CREATION: "STREAM_ARTICLE_CREATION",
        REPORT_GENERATION: "REPORT_GENERATION"
    }
}
